//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuchIntegrationEF.Objects.Custom.Entities
{
    public partial class Balance {

        public Balance()
        {
            this.BalanceHistories = new List<BalanceHistory>();
            this.BalanceChannels = new List<BalanceChannel>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Name
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int PermissibleUnbalance
        {
            get;
            set;
        }

        public virtual DateTimeOffset? TimeStampCreate
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid FacilityId
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid ResourceTypeId
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid CreatorId
        {
            get;
            set;
        }

        public virtual IList<BalanceHistory> BalanceHistories
        {
            get;
            set;
        }

        public virtual IList<BalanceChannel> BalanceChannels
        {
            get;
            set;
        }

        [ForeignKey(nameof(FacilityId))]
        public virtual Facility Facility
        {
            get;
            set;
        }

        [ForeignKey(nameof(ResourceTypeId))]
        public virtual DeviceType ResourceType
        {
            get;
            set;
        }

        [ForeignKey(nameof(CreatorId))]
        public virtual Contractor Creator
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
