//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuchIntegrationEF.Objects.Custom.Entities
{
    public partial class Facility {

        public Facility()
        {
            this.Childs = new List<Facility>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string AddressString
        {
            get;
            set;
        }

        public virtual string Room
        {
            get;
            set;
        }

        public virtual short? Floor
        {
            get;
            set;
        }

        public virtual short? Porch
        {
            get;
            set;
        }

        public virtual string Note
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid CreatorId
        {
            get;
            set;
        }
        
        public virtual Guid? SubscriberId
        {
            get;
            set;
        }

        public virtual Guid? TerritoryId
        {
            get;
            set;
        }

        public virtual Guid? ParentId
        {
            get;
            set;
        }

        public virtual IList<Facility> Childs
        {
            get;
            set;
        }

        [ForeignKey(nameof(ParentId))]
        public virtual Facility Parent
        {
            get;
            set;
        }

        [ForeignKey(nameof(CreatorId))]
        public virtual Contractor Creator
        {
            get;
            set;
        }

        [ForeignKey(nameof(SubscriberId))]
        public virtual Contractor Subscriber
        {
            get;
            set;
        }

        [ForeignKey(nameof(TerritoryId))]
        public virtual Territory Territory
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
