//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;
using LuchIntegrationEF.Objects.Custom.Enums;

namespace LuchIntegrationEF.Objects.Custom.Entities
{
    public partial class Report {

        public Report()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual System.DateTimeOffset TimeStampCreate
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual System.DateTimeOffset TimeStampComplete
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual FileFormat FileFormat
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual ReportState State
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Property
        {
            get;
            set;
        }

        public virtual bool Private
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid ReportVersionId
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid CreatorId
        {
            get;
            set;
        }
        
        public virtual Guid? ReportFileId
        {
            get;
            set;
        }

        [ForeignKey(nameof(ReportVersionId))]
        public virtual ReportVersion ReportVersion
        {
            get;
            set;
        }

        [ForeignKey(nameof(CreatorId))]
        public virtual Contractor Creator
        {
            get;
            set;
        }

        [ForeignKey(nameof(ReportFileId))]
        public virtual ReportFile ReportFile
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
