//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuchIntegrationEF.Objects.Custom.Entities
{
    public partial class Territory {

        public Territory()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Name
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Index
        {
            get;
            set;
        }

        public virtual string Type
        {
            get;
            set;
        }

        public virtual Guid? FiasId
        {
            get;
            set;
        }

        public virtual Guid? CountryId
        {
            get;
            set;
        }

        public virtual Guid? RegionId
        {
            get;
            set;
        }

        public virtual Guid? AOkrug
        {
            get;
            set;
        }

        public virtual Guid? RayonId
        {
            get;
            set;
        }

        public virtual Guid? CityId
        {
            get;
            set;
        }

        public virtual Guid? TownId
        {
            get;
            set;
        }

        public virtual Guid? MRayonId
        {
            get;
            set;
        }

        public virtual Guid? StreetId
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid AddressLevelId
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual Guid AddressTypeId
        {
            get;
            set;
        }

        [ForeignKey(nameof(AddressLevelId))]
        public virtual AddressLevel AddressLevel
        {
            get;
            set;
        }

        [ForeignKey(nameof(AddressTypeId))]
        public virtual AddressType AddressType
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
