//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace LuchIntegrationEF.Objects.Custom.Enums
{
    public enum FileFormat : int
    {
        xlsx,
        pdf
    }
}
