//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace LuchIntegrationEF.Objects.Custom.Enums
{
    public enum MeasuredResource : int
    {
        // Добавлять можно, но МЕНЯТЬ НЕЛЬЗЯ!
        Electricity = 0,
        Water = 1,
        HotWater = 2,
        ColdWater = 3,
        Gas = 4,
        Heat = 5,
        Impulse = 6,
        Unknown = 7,
        SmartLight = 8
    }
}
