//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// ''
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace LuchIntegrationEF.Objects.Custom.Enums
{
    public enum TypeСontractorRole : int
    {
        Administration = 0,
        Partner = 1,
        Client = 2,
        Subscriber = 3,
        RSO = 4,
        Unknown = 5
    }
}
